### ISSUE TITLE
fuzzy-time-0.3.0.0 fails to compile with ghc-9.12.2

### ISSUE THREAD

**Issue by juhp** [NorfairKing/fuzzy-time#8]
For Stackage Nightly:

```
       /home/curators/work/unpack-dir/unpacked/fuzzy-time-0.3.0.0-75951ca51ea15635fbc416aad422185f79aa7393c62ecf74be0b4bd665b992de/s
rc/Data/FuzzyTime/Types.hs:127:1: error: [GHC-59692]
           Duplicate instance declarations:
             instance Generic DayOfWeek
               -- Defined at src/Data/FuzzyTime/Types.hs:127:1
             instance [safe] Generic DayOfWeek
               -- Defined in ‘time-1.14:Data.Time.Calendar.Week’
           |
       127 | deriving instance Generic DayOfWeek
           | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by NorfairKing** [comment]
I just released fuzzy-time 0.3.0.1 in which this is fixed.
